//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerrLauncherPackCreator.Resources.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TerrLauncherPackCreator.Resources.Localizations.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddAuthorCaption {
            get {
                return ResourceManager.GetString("AddAuthorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors.
        /// </summary>
        public static string Authors {
            get {
                return ResourceManager.GetString("Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack is not selected!.
        /// </summary>
        public static string ChoosePackDialogFailed {
            get {
                return ResourceManager.GetString("ChoosePackDialogFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TerrLauncher packs.
        /// </summary>
        public static string ChoosePackDialogFilter {
            get {
                return ResourceManager.GetString("ChoosePackDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a pack:.
        /// </summary>
        public static string ChoosePackDialogTitle {
            get {
                return ResourceManager.GetString("ChoosePackDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack download started.
        /// </summary>
        public static string ChoosePackProcessStarted {
            get {
                return ResourceManager.GetString("ChoosePackProcessStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File type:.
        /// </summary>
        public static string ConverterFileType {
            get {
                return ResourceManager.GetString("ConverterFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string DeleteAuthorCaption {
            get {
                return ResourceManager.GetString("DeleteAuthorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string DeletePreviewCaption {
            get {
                return ResourceManager.GetString("DeletePreviewCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag an icon here (.png).
        /// </summary>
        public static string DragAuthorImageHelpText {
            get {
                return ResourceManager.GetString("DragAuthorImageHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag an icon here (.png|.gif).
        /// </summary>
        public static string DragIconHelpText {
            get {
                return ResourceManager.GetString("DragIconHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag files here.
        /// </summary>
        public static string DragModifiedFilesHelpText {
            get {
                return ResourceManager.GetString("DragModifiedFilesHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag images here (.jpg|.png|.gif).
        /// </summary>
        public static string DragPreviewsHelpText {
            get {
                return ResourceManager.GetString("DragPreviewsHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditAuthorCaption {
            get {
                return ResourceManager.GetString("EditAuthorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorLower {
            get {
                return ResourceManager.GetString("ErrorLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error encountered: {0}.
        /// </summary>
        public static string ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string InformationLower {
            get {
                return ResourceManager.GetString("InformationLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t load an icon from the file. Error: &quot;{0}&quot;.
        /// </summary>
        public static string LoadIconFromFileFailed {
            get {
                return ResourceManager.GetString("LoadIconFromFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can;t load an image from the file: &quot;{0}&quot;. Error: &quot;{1}&quot;.
        /// </summary>
        public static string LoadImageFromFileFailed {
            get {
                return ResourceManager.GetString("LoadImageFromFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading packs.
        /// </summary>
        public static string LoadingProgressStep {
            get {
                return ResourceManager.GetString("LoadingProgressStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified files.
        /// </summary>
        public static string ModifiedFiles {
            get {
                return ResourceManager.GetString("ModifiedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string NewGuidCaption {
            get {
                return ResourceManager.GetString("NewGuidCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string NextStepCaption {
            get {
                return ResourceManager.GetString("NextStepCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t open the link in the browser: {0}.
        /// </summary>
        public static string OpenLinkInBrowserFailed {
            get {
                return ResourceManager.GetString("OpenLinkInBrowserFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string PackCreateNew {
            get {
                return ResourceManager.GetString("PackCreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description (in English).
        /// </summary>
        public static string PackDescriptionEnglish {
            get {
                return ResourceManager.GetString("PackDescriptionEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description (in Russian).
        /// </summary>
        public static string PackDescriptionRussian {
            get {
                return ResourceManager.GetString("PackDescriptionRussian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE RESULT.
        /// </summary>
        public static string PackExport {
            get {
                return ResourceManager.GetString("PackExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack &quot;{0}&quot; is saved. Show in explorer?.
        /// </summary>
        public static string PackExported {
            get {
                return ResourceManager.GetString("PackExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guid:.
        /// </summary>
        public static string PackGuid {
            get {
                return ResourceManager.GetString("PackGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing.
        /// </summary>
        public static string PackLoadExisting {
            get {
                return ResourceManager.GetString("PackLoadExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t load the pack &quot;{0}&quot;. Error: &quot;{1}&quot;.
        /// </summary>
        public static string PackLoadingFailed {
            get {
                return ResourceManager.GetString("PackLoadingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack structure version:.
        /// </summary>
        public static string PackStructureVersion {
            get {
                return ResourceManager.GetString("PackStructureVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string PackTitle {
            get {
                return ResourceManager.GetString("PackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        public static string PackTypeAudio {
            get {
                return ResourceManager.GetString("PackTypeAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters.
        /// </summary>
        public static string PackTypeCharacters {
            get {
                return ResourceManager.GetString("PackTypeCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonts.
        /// </summary>
        public static string PackTypeFonts {
            get {
                return ResourceManager.GetString("PackTypeFonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gui.
        /// </summary>
        public static string PackTypeGui {
            get {
                return ResourceManager.GetString("PackTypeGui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack type.
        /// </summary>
        public static string PackTypeHelpText {
            get {
                return ResourceManager.GetString("PackTypeHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maps.
        /// </summary>
        public static string PackTypeMaps {
            get {
                return ResourceManager.GetString("PackTypeMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack type is not selected!.
        /// </summary>
        public static string PackTypeNotSelected {
            get {
                return ResourceManager.GetString("PackTypeNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textures.
        /// </summary>
        public static string PackTypeTextures {
            get {
                return ResourceManager.GetString("PackTypeTextures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translations.
        /// </summary>
        public static string PackTypeTranslations {
            get {
                return ResourceManager.GetString("PackTypeTranslations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string PackVersion {
            get {
                return ResourceManager.GetString("PackVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previews.
        /// </summary>
        public static string Previews {
            get {
                return ResourceManager.GetString("Previews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string PreviousStepCaption {
            get {
                return ResourceManager.GetString("PreviousStepCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converter.
        /// </summary>
        public static string ResourcesConverter {
            get {
                return ResourceManager.GetString("ResourcesConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path is not selected!.
        /// </summary>
        public static string SavePackDialogFailed {
            get {
                return ResourceManager.GetString("SavePackDialogFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TerrLauncher packs.
        /// </summary>
        public static string SavePackDialogFilter {
            get {
                return ResourceManager.GetString("SavePackDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose result file path:.
        /// </summary>
        public static string SavePackDialogTitle {
            get {
                return ResourceManager.GetString("SavePackDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t save the pack: &quot;{0}&quot;. Error: &quot;{1}&quot;.
        /// </summary>
        public static string SavingPackFailed {
            get {
                return ResourceManager.GetString("SavingPackFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining.
        /// </summary>
        public static string SavingProcessRemaining {
            get {
                return ResourceManager.GetString("SavingProcessRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving packs.
        /// </summary>
        public static string SavingProcessStep {
            get {
                return ResourceManager.GetString("SavingProcessStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terraria structure version:.
        /// </summary>
        public static string TerrariaStructureVersion {
            get {
                return ResourceManager.GetString("TerrariaStructureVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TerLauncher pack.
        /// </summary>
        public static string TlPacksFilter {
            get {
                return ResourceManager.GetString("TlPacksFilter", resourceCulture);
            }
        }
    }
}
