//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerrLauncherPackCreator.Resources.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TerrLauncherPackCreator.Resources.Localizations.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string DeletePreviewCaption {
            get {
                return ResourceManager.GetString("DeletePreviewCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перетащите иконку сюда (.png).
        /// </summary>
        public static string DragIconHelpText {
            get {
                return ResourceManager.GetString("DragIconHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перетащите файлы сюда.
        /// </summary>
        public static string DragModifiedFilesHelpText {
            get {
                return ResourceManager.GetString("DragModifiedFilesHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перетащите изображения сюда (.jpg).
        /// </summary>
        public static string DragPreviewsHelpText {
            get {
                return ResourceManager.GetString("DragPreviewsHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        public static string ErrorLower {
            get {
                return ResourceManager.GetString("ErrorLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось загрузить иконку из файла. Ошибка: &quot;{0}&quot;.
        /// </summary>
        public static string LoadIconFromFileFailed {
            get {
                return ResourceManager.GetString("LoadIconFromFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось загрузить изображение из файла: &quot;{0}&quot;. Ошибка: &quot;{1}&quot;.
        /// </summary>
        public static string LoadImageFromFileFailed {
            get {
                return ResourceManager.GetString("LoadImageFromFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменённые файлы.
        /// </summary>
        public static string ModifiedFiles {
            get {
                return ResourceManager.GetString("ModifiedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый.
        /// </summary>
        public static string NewGuidCaption {
            get {
                return ResourceManager.GetString("NewGuidCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вперёд.
        /// </summary>
        public static string NextStepCaption {
            get {
                return ResourceManager.GetString("NextStepCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to НОВЫЙ.
        /// </summary>
        public static string PackCreateNew {
            get {
                return ResourceManager.GetString("PackCreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание (на английском).
        /// </summary>
        public static string PackDescriptionEnglish {
            get {
                return ResourceManager.GetString("PackDescriptionEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание (на русском).
        /// </summary>
        public static string PackDescriptionRussian {
            get {
                return ResourceManager.GetString("PackDescriptionRussian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to СОХРАНИТЬ ГОТОВЫЙ.
        /// </summary>
        public static string PackExport {
            get {
                return ResourceManager.GetString("PackExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guid:.
        /// </summary>
        public static string PackGuid {
            get {
                return ResourceManager.GetString("PackGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to СУЩЕСТВУЮЩИЙ.
        /// </summary>
        public static string PackLoadExisting {
            get {
                return ResourceManager.GetString("PackLoadExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string PackTitle {
            get {
                return ResourceManager.GetString("PackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия:.
        /// </summary>
        public static string PackVersion {
            get {
                return ResourceManager.GetString("PackVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Превью.
        /// </summary>
        public static string Previews {
            get {
                return ResourceManager.GetString("Previews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        public static string PreviousStepCaption {
            get {
                return ResourceManager.GetString("PreviousStepCaption", resourceCulture);
            }
        }
    }
}
