//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerrLauncherPackCreator.Resources.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TerrLauncherPackCreator.Resources.Localizations.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        public static string AddAuthorCaption {
            get {
                return ResourceManager.GetString("AddAuthorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авторы.
        /// </summary>
        public static string Authors {
            get {
                return ResourceManager.GetString("Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пак не выбран!.
        /// </summary>
        public static string ChoosePackDialogFailed {
            get {
                return ResourceManager.GetString("ChoosePackDialogFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паки TerrLauncher.
        /// </summary>
        public static string ChoosePackDialogFilter {
            get {
                return ResourceManager.GetString("ChoosePackDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите пак:.
        /// </summary>
        public static string ChoosePackDialogTitle {
            get {
                return ResourceManager.GetString("ChoosePackDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка пака началась.
        /// </summary>
        public static string ChoosePackProcessStarted {
            get {
                return ResourceManager.GetString("ChoosePackProcessStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string DeleteAuthorCaption {
            get {
                return ResourceManager.GetString("DeleteAuthorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string DeletePreviewCaption {
            get {
                return ResourceManager.GetString("DeletePreviewCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перетащите иконку сюда (.png).
        /// </summary>
        public static string DragAuthorImageHelpText {
            get {
                return ResourceManager.GetString("DragAuthorImageHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перетащите иконку сюда (.png|.gif).
        /// </summary>
        public static string DragIconHelpText {
            get {
                return ResourceManager.GetString("DragIconHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перетащите файлы сюда.
        /// </summary>
        public static string DragModifiedFilesHelpText {
            get {
                return ResourceManager.GetString("DragModifiedFilesHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перетащите изображения сюда (.jpg|.png|.gif).
        /// </summary>
        public static string DragPreviewsHelpText {
            get {
                return ResourceManager.GetString("DragPreviewsHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить.
        /// </summary>
        public static string EditAuthorCaption {
            get {
                return ResourceManager.GetString("EditAuthorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        public static string ErrorLower {
            get {
                return ResourceManager.GetString("ErrorLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обнаружена ошибка: {0}.
        /// </summary>
        public static string ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация.
        /// </summary>
        public static string InformationLower {
            get {
                return ResourceManager.GetString("InformationLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось загрузить иконку из файла. Ошибка: &quot;{0}&quot;.
        /// </summary>
        public static string LoadIconFromFileFailed {
            get {
                return ResourceManager.GetString("LoadIconFromFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось загрузить изображение из файла: &quot;{0}&quot;. Ошибка: &quot;{1}&quot;.
        /// </summary>
        public static string LoadImageFromFileFailed {
            get {
                return ResourceManager.GetString("LoadImageFromFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка паков.
        /// </summary>
        public static string LoadingProgressStep {
            get {
                return ResourceManager.GetString("LoadingProgressStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лог.
        /// </summary>
        public static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменённые файлы.
        /// </summary>
        public static string ModifiedFiles {
            get {
                return ResourceManager.GetString("ModifiedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый.
        /// </summary>
        public static string NewGuidCaption {
            get {
                return ResourceManager.GetString("NewGuidCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вперёд.
        /// </summary>
        public static string NextStepCaption {
            get {
                return ResourceManager.GetString("NextStepCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to НОВЫЙ.
        /// </summary>
        public static string PackCreateNew {
            get {
                return ResourceManager.GetString("PackCreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание (на английском).
        /// </summary>
        public static string PackDescriptionEnglish {
            get {
                return ResourceManager.GetString("PackDescriptionEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание (на русском).
        /// </summary>
        public static string PackDescriptionRussian {
            get {
                return ResourceManager.GetString("PackDescriptionRussian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to СОХРАНИТЬ ГОТОВЫЙ.
        /// </summary>
        public static string PackExport {
            get {
                return ResourceManager.GetString("PackExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пак &quot;{0}&quot; сохранён. Показать в проводнике?.
        /// </summary>
        public static string PackExported {
            get {
                return ResourceManager.GetString("PackExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guid:.
        /// </summary>
        public static string PackGuid {
            get {
                return ResourceManager.GetString("PackGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to СУЩЕСТВУЮЩИЙ.
        /// </summary>
        public static string PackLoadExisting {
            get {
                return ResourceManager.GetString("PackLoadExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось загрузить пак &quot;{0}&quot;. Ошибка: &quot;{1}&quot;.
        /// </summary>
        public static string PackLoadingFailed {
            get {
                return ResourceManager.GetString("PackLoadingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string PackTitle {
            get {
                return ResourceManager.GetString("PackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аудио.
        /// </summary>
        public static string PackTypeAudio {
            get {
                return ResourceManager.GetString("PackTypeAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Персонажи.
        /// </summary>
        public static string PackTypeCharacters {
            get {
                return ResourceManager.GetString("PackTypeCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шрифты.
        /// </summary>
        public static string PackTypeFonts {
            get {
                return ResourceManager.GetString("PackTypeFonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gui.
        /// </summary>
        public static string PackTypeGui {
            get {
                return ResourceManager.GetString("PackTypeGui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип пака.
        /// </summary>
        public static string PackTypeHelpText {
            get {
                return ResourceManager.GetString("PackTypeHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Карты.
        /// </summary>
        public static string PackTypeMaps {
            get {
                return ResourceManager.GetString("PackTypeMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип пака не выбран!.
        /// </summary>
        public static string PackTypeNotSelected {
            get {
                return ResourceManager.GetString("PackTypeNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текстуры.
        /// </summary>
        public static string PackTypeTextures {
            get {
                return ResourceManager.GetString("PackTypeTextures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переводы.
        /// </summary>
        public static string PackTypeTranslations {
            get {
                return ResourceManager.GetString("PackTypeTranslations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия:.
        /// </summary>
        public static string PackVersion {
            get {
                return ResourceManager.GetString("PackVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Превью.
        /// </summary>
        public static string Previews {
            get {
                return ResourceManager.GetString("Previews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        public static string PreviousStepCaption {
            get {
                return ResourceManager.GetString("PreviousStepCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Путь не выбран!.
        /// </summary>
        public static string SavePackDialogFailed {
            get {
                return ResourceManager.GetString("SavePackDialogFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паки TerrLauncher.
        /// </summary>
        public static string SavePackDialogFilter {
            get {
                return ResourceManager.GetString("SavePackDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите путь к готовому паку:.
        /// </summary>
        public static string SavePackDialogTitle {
            get {
                return ResourceManager.GetString("SavePackDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось сохранить пак: &quot;{0}&quot;. Ошибка: &quot;{1}&quot;.
        /// </summary>
        public static string SavingPackFailed {
            get {
                return ResourceManager.GetString("SavingPackFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Осталось.
        /// </summary>
        public static string SavingProcessRemaining {
            get {
                return ResourceManager.GetString("SavingProcessRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранение паков.
        /// </summary>
        public static string SavingProcessStep {
            get {
                return ResourceManager.GetString("SavingProcessStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия структуры террарии:.
        /// </summary>
        public static string TerrariaStructureVersion {
            get {
                return ResourceManager.GetString("TerrariaStructureVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пак TerLauncher.
        /// </summary>
        public static string TlPacksFilter {
            get {
                return ResourceManager.GetString("TlPacksFilter", resourceCulture);
            }
        }
    }
}
