name: Heavy build

on:
  workflow_dispatch:
  push:
    tags:
      - "**"

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
  
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Publish framework dependent creator
      # dotnet command can not handle some of pubxml profiles' data. Using plain commands just to not have to much headache
      run: dotnet publish TerrLauncherPackCreator/TerrLauncherPackCreator.csproj --configuration Release --runtime win-x64 -p:PublishSingleFile=true --self-contained false

    - name: Publish framework dependent updater
      # dotnet command can not handle some of pubxml profiles' data. Using plain commands just to not have to much headache
      run: dotnet publish TerrLauncherPackCreatorUpdater/TerrLauncherPackCreatorUpdater.csproj --configuration Release --runtime win-x64 -p:PublishSingleFile=true --self-contained false

    - name: Copy all files into upload directory
      # mkdir -p creates all directories in path
      run: |
        mkdir -p to_upload/data
        cp TerrLauncherPackCreator/bin/Release/net9.0-windows/win-x64/publish/TerrLauncherPackCreator.exe to_upload/data/TerrLauncherPackCreator.exe
        cp TerrLauncherPackCreator/bin/Release/net9.0-windows/win-x64/publish/libwebp_x64.dll to_upload/data/libwebp_x64.dll
        cp TerrLauncherPackCreatorUpdater/bin/Release/net9.0-windows/win-x64/publish/updater.exe to_upload/data/updater.exe
        mkdir -p to_upload/installer
        cp TerrLauncherPackCreatorUpdater/bin/Release/net9.0-windows/win-x64/publish/updater.exe to_upload/installer/installer.exe

    - name: Upload data
      uses: actions/upload-artifact@v4
      with:
        name: data-net-9.0-windows-x64-framework-dependent
        path: to_upload/data/**
        if-no-files-found: error
        
    - name: Upload installer
      uses: actions/upload-artifact@v4
      with:
        name: installer-net-9.0-windows-x64-framework-dependent
        path: to_upload/installer/**
        if-no-files-found: error
