name: Heavy build

on:
  workflow_dispatch:
  push:
    branches: [ "releases/**" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
  
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Publish framework dependent creator
      run: dotnet publish /p:PublishProfile=creator-net-7.0-windows-x64-framework-dependent.pubxml

    - name: Publish framework dependent updater
      run: dotnet publish /p:PublishProfile=updater-net-7.0-windows-x64-framework-dependent.pubxml

    - name: Copy all files into uplod directory
      run: |
        mkdir to_upload
        cp TerrLauncherPackCreator/bin/Release/net7.0-windows/publish/win-x64/TerrLauncherPackCreator.exe to_upload/TerrLauncherPackCreator.exe
        cp TerrLauncherPackCreator/bin/Release/net7.0-windows/publish/win-x64/libwebp_x64.dll to_upload/libwebp_x64.dll
        echo ".. >>"
        ls ..
        echo "TerrLauncherPackCreatorUpdater >>"
        ls TerrLauncherPackCreatorUpdater
        echo "TerrLauncherPackCreatorUpdater/bin >>"
        ls TerrLauncherPackCreatorUpdater/bin
        echo "TerrLauncherPackCreatorUpdater/bin/Release >>"
        ls TerrLauncherPackCreatorUpdater/bin/Release
        echo "TerrLauncherPackCreatorUpdater/bin/Release/net7.0-windows >>"
        ls TerrLauncherPackCreatorUpdater/bin/Release/net7.0-windows
        echo "TerrLauncherPackCreatorUpdater/bin/Release/net7.0-windows/publish >>"
        ls TerrLauncherPackCreatorUpdater/bin/Release/net7.0-windows/publish
        cp TerrLauncherPackCreatorUpdater/bin/Release/net7.0-windows/publish/updater.exe to_upload/updater.exe

    - name: Upload framework dependent
      uses: actions/upload-artifact@v3
      with:
        name: net-7.0-windows-x64-framework-dependent
        path: to_upload/**
        if-no-files-found: error
